apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: aplikacja
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
