apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: generate-sbom
  namespace: aplikacja-cicd
spec:
  params:
    - name: image
      type: string
  workspaces:
    - name: source
  steps:
    - name: generate-sbom
      image: anchore/syft:latest
      script: |
        #!/bin/sh
        set -e
        echo "=== Generating SBOM for $(params.image) ==="
        syft registry:$(params.image) -o spdx-json > $(workspaces.source.path)/sbom.spdx.json
        echo "=== SBOM generated ==="
        echo "SBOM size: $(wc -c < $(workspaces.source.path)/sbom.spdx.json) bytes"
