apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: push-sbom
  namespace: aplikacja-cicd
spec:
  params:
    - name: image
      type: string
  workspaces:
    - name: shared-data
  steps:
    - name: push-sbom
      image: bitnami/cosign:latest
      script: |
        #!/bin/sh
        set -e
        SBOM_FILE=$(workspaces.shared-data.path)/sbom.spdx.json
        echo "=== Attaching SBOM to $(params.image) ==="
        cosign attach sbom --sbom "${SBOM_FILE}" --type spdx "$(params.image)" --allow-http-registry --allow-insecure-registry
        echo "=== SBOM attached to image ==="
